# .github/workflows/main.yml

name: Scrape Eventbrite IDs

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Runs the workflow every day at midnight UTC
  schedule:
    - cron: '0 0 * * *'

  # Optional: Runs the workflow on pushes to the main branch
  # Useful for initial setup and testing
  push:
    branches:
      - main

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Check out repository
        uses: actions/checkout@v4

      - name: 2. Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # You can specify any Python 3.x version

      - name: 3. Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 4. Run the scraper script
        run: |
          # Assuming your Python script is named 'scraper.py'
          python scraper.py # <-- IMPORTANT: Change this to your script's filename

      - name: 5. Commit and push if there are changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add eventbrite_event_ids_requests.csv # Add the generated file
          
          # Check if there are any changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update Eventbrite IDs CSV"
            git push
          fi