# .github/workflows/main.yml

name: Scrape Eventbrite IDs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  scrape:
    runs-on: ubuntu-latest

    # Add this permissions block to grant write access
    permissions:
      contents: write

    steps:
      - name: 1. Check out repository
        uses: actions/checkout@v4

      - name: 2. Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 4. Run the scraper script
        run: |
          python scraper.py # <-- Remember to use your script's filename

      - name: 5. Commit and push if CSV exists and has changed
        run: |
          if [ ! -f eventbrite_event_ids_requests.csv ]; then
            echo "Scraper did not create the CSV file. This may be because no new events were found or an error occurred during scraping."
            echo "Exiting gracefully."
            exit 0
          fi
          
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add eventbrite_event_ids_requests.csv
          
          if git diff --staged --quiet; then
            echo "No changes to commit. The event list is up-to-date."
          else
            git commit -m "Update Eventbrite IDs CSV"
            git push
          fi